development:
  react_cors: true
  database:
    table: asira_lender
    username: asirauser
    password: asirapass
    host: postgres_db
    port: "5432"
    maxlifetime: 30
    idle_conns: 10
    open_conns: 100
    sslmode: disable
    logmode: true
    timezone: Asia/Jakarta
  kafka:
    host: kafka
    port: "9092"
    user: asirauser
    pass: asirapass
    client_id: asira
    sasl: false
    log_verbose: true
    topics:
      produces:
        for_borrower: asira_lender_to_borrower
      consumes:
        for_lender: asira_borrower_to_lender
  jwt:
    duration: 120 # in minutes
    jwt_secret: sXQ8jUMpueOvN5P3cdCR
  s3:
    debug_mode: 1
    access_key: fawef23fawf3f
    secret_key: fa3wfaq3fadesefawe43f
    host: https://s3.amazon.com:8080
    bucket_name: bucks
  northstar:
    secret: bGVuZGVya2V5OmxlbmRlcnNlY3JldA==
    topic: northstar_logger
    send: true

staging:

production: